chairs = {
    ['chairs'] = {
    label = "Chair's",
    items = {
        [1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["label"] = "High chair" },
        [2] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 500, ["label"] = "Sitchair 4" },
        [3] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["label"] = "Chairl" },
        [4] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["label"] = "Chair 2" },
        [5] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["label"] = "High chair 2" },
        [6] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["label"] = "Kitchen chair 1" },
        [7] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["label"] = "Kitchen chair 2" },
        [8] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["label"] = "Kitchen chair 3" },
        [9] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["label"] = "Chair 3" },
        [10] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["label"] = "Chair 4" },
        [11] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["label"] = "High chair 3" },
        [12] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["label"] = "Arm Chair" },
        [13] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["label"] = "Kitchen chair 4" },
        [14] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["label"] = "Chair 5" },
        [15] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["label"] = "MB Chair" },
        [16] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["label"] = "Arm Chair 2" },
        [17] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["label"] = "Kitchen chair 5" },
        [18] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["label"] = "Study Chair" },
        [19] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["label"] = "Chair frame" },
        [20] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["label"] = "Chair 5" },
        [21] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["label"] = "officeChair" },
        [22] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["label"] = "Chair 6" },
        [23] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["label"] = "Lether Chair" },
        [24] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["label"] = "Chair Scuz" },
        [25] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["label"] = "DeskChair" },
        [26] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["label"] = "Easy Chair" },
        [27] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["label"] = "Whicker Chair" },
        [28] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["label"] = "Direct Chair" },
        [29] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["label"] = "Direct Chair 2" },
        [30] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["label"] = "Yacht Chair 1" },
        [31] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["label"] = "Yacht Chair 2" },
        [32] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["label"] = "Yacht Chair 3" },
        [33] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["label"] = "Yacht Chair 4" },
        [34] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["label"] = "White Chair" },
        [35] = { ["object"] = "v_ret_chair", ["price"] = 100, ["label"] = "Chair 7" },
        [36] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["label"] = "TA Chair" },
        [37] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["label"] = "office Chair 2" },
        [38] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 1000, ["label"] = "White fauteuil" },
        -- [39] = { ["object"] = "v_club_barchair", ["price"] = 300, ["label"] = "Chair 8" },
        [39] = { ["object"] = "prop_off_chair_04", ["price"] = 300, ["label"] = "Desk Chair 2" },
        -- [40] = { ["object"] = "v_club_stagechair", ["price"] = 500, ["label"] = "fauteuil roze" },
        [40] = { ["object"] = "v_club_officechair", ["price"] = 500, ["label"] = "Desk Chair 3" },
        [41] = { ["object"] = "prop_armchair_01", ["price"] = 500, ["label"] = "Sit chair" },
        [42] = { ["object"] = "prop_bar_stool_01", ["price"] = 300, ["label"] = "Barstool" },
        [43] = { ["object"] = "apa_mp_h_yacht_stool_01", ["price"] = 300, ["label"] = "White pouffe" },
        [44] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 500, ["label"] = "Sitchair 3" },
        [45] = { ["object"] = "apa_mp_h_stn_chairstool_12", ["price"] = 300, ["label"] = "Feet support" },
        [46] = { ["object"] = "prop_chair_03", ["price"] = 100, ["label"] = "Wooden Chair" },
        [47] = { ["object"] = "prop_couch_sm_05", ["price"] = 500, ["label"] = "corduroy armchair" },
        [48] = { ["object"] = "prop_couch_sm_07", ["price"] = 300, ["label"] = "white armchair 2" },
        [49] = { ["object"] = "prop_couch_sm_02", ["price"] = 300, ["label"] = "orange armchair" },
        [50] = { ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 500, ["label"] = "lounge chair" },
        [51] = { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 500, ["label"] = "lounge chair 2" },
        [52] = { ["object"] = "apa_mp_h_din_chair_04", ["price"] = 500, ["label"] = "modern chair" },
        [53] = { ["object"] = "apa_mp_h_din_chair_08", ["price"] = 500, ["label"] = "modern chair 2" },
        [54] = { ["object"] = "apa_mp_h_din_chair_09", ["price"] = 500, ["label"] = "modern chair 3" },
        [55] = { ["object"] = "apa_mp_h_din_chair_12", ["price"] = 500, ["label"] = "modern chair 4" },
        [56] = { ["object"] = "apa_mp_h_din_stool_04", ["price"] = 500, ["label"] = "modern chair 5" },
        [57] = { ["object"] = "apa_mp_h_stn_chairarm_01", ["price"] = 500, ["label"] = "modern chair 6" },
        [58] = { ["object"] = "apa_mp_h_stn_chairarm_02", ["price"] = 500, ["label"] = "modern chair 7" },
        [59] = { ["object"] = "apa_mp_h_stn_chairarm_03", ["price"] = 500, ["label"] = "modern chair 8" },
        [60] = { ["object"] = "apa_mp_h_stn_chairarm_09", ["price"] = 500, ["label"] = "modern chair 9" },
        [61] = { ["object"] = "apa_mp_h_stn_chairarm_11", ["price"] = 500, ["label"] = "modern chair 10" },
        [62] = { ["object"] = "apa_mp_h_stn_chairarm_13", ["price"] = 500, ["label"] = "modern chair 11" },
        [63] = { ["object"] = "apa_mp_h_stn_chairarm_24", ["price"] = 500, ["label"] = "modern chair 12" },
        [64] = { ["object"] = "apa_mp_h_stn_chairarm_25", ["price"] = 500, ["label"] = "modern chair 13" },
        [65] = { ["object"] = "apa_mp_h_stn_chairarm_26", ["price"] = 500, ["label"] = "modern chair 14" },
        [66] = { ["object"] = "apa_mp_h_stn_chairstrip_04", ["price"] = 500, ["label"] = "modern chair 15" },
        [67] = { ["object"] = "apa_mp_h_stn_chairstrip_05", ["price"] = 500, ["label"] = "modern chair 16" },
        [68] = { ["object"] = "apa_mp_h_stn_chairstrip_08", ["price"] = 500, ["label"] = "modern chair 17" },
        [69] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 500, ["label"] = "pouffe" },
        [70] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 500, ["label"] = "pouffe 2" },
        [71] = { ["object"] = "apa_mp_h_yacht_barstool_01", ["price"] = 500, ["label"] = "barstool 2" },
        [72] = { ["object"] = "ba_prop_int_glam_stool", ["price"] = 500, ["label"] = "barstool 3" },
        [73] = { ["object"] = "ba_prop_battle_club_chair_01", ["price"] = 500, ["label"] = "office chair" },
        [74] = { ["object"] = "ba_prop_battle_club_chair_02", ["price"] = 500, ["label"] = "office chair 2" },
        [75] = { ["object"] = "ba_prop_battle_club_chair_03", ["price"] = 500, ["label"] = "office chair 3" },
        [76] = { ["object"] = "ba_prop_battle_control_seat", ["price"] = 500, ["label"] = "gaming chair" }			
    },
},}