electronics = {
    ['electronics'] = {
    label = "Electronics",
    items = {
        [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["label"] = "Old Fridge" },
        [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["label"] = "Speaker" },
        [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["label"] = "Speaker Dock" },
        [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["label"] = "Bedside Clock" },
        [5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["label"] = "Phone" },
        [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["label"] = "Tower Fan" },
        [7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["label"] = "Fan" },
        [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["label"] = "Bigscreen" },
        [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["label"] = "Monitor" },
        [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["label"] = "Mixer" },
        [11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["label"] = "CCTV" },
        [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["label"] = "Laptop" },
        [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["label"] = "Monitor" },
        [14] = { ["object"] = "prop_speaker_05", ["price"] = 500, ["label"] = "mounted speaker" },
        [15] = { ["object"] = "prop_tv_flat_03b", ["price"] = 1000, ["label"] = "kleine flatscreen" },
        [16] = { ["object"] = "prop_laptop_01a", ["price"] = 750, ["label"] = "Open laptop" },
        [17] = { ["object"] = "prop_tv_flat_michael", ["price"] = 3000, ["label"] = "flatscreen hanging ing" },
        [18] = { ["object"] = "prop_dyn_pc", ["price"] = 1000, ["label"] = "pc" },
        [19] = { ["object"] = "prop_keyboard_01b", ["price"] = 100, ["label"] = "Keybord" },
        [20] = { ["object"] = "prop_mouse_01b", ["price"] = 100, ["label"] = "Computer mouse" },
        [21] = { ["object"] = "v_ret_gc_phone", ["price"] = 100, ["label"] = "office phone" },
        [22] = { ["object"] = "prop_tv_flat_01", ["price"] = 5000, ["label"] = "Big flatscreen" },
        [23] = { ["object"] = "prop_arcade_01", ["price"] = 5000, ["label"] = "arcade" },
        [24] = { ["object"] = "prop_console_01", ["price"] = 250, ["label"] = "gameconsole" },
        [25] = { ["object"] = "v_res_tre_dvdplayer", ["price"] = 250, ["label"] = "dvd Player" },
        [26] = { ["object"] = "prop_speaker_08", ["price"] = 500, ["label"] = "wooden speaker" },
        [27] = { ["object"] = "prop_cctv_mon_02", ["price"] = 300, ["label"] = "cctv monitor" },
        [28] = { ["object"] = "prop_tv_flat_02", ["price"] = 2500, ["label"] = "flatscreen Standing" },
        [29] = { ["object"] = "prop_cctv_cam_01a", ["price"] = 300, ["label"] = "cctv 2" },
        [30] = { ["object"] = "prop_dest_cctv_02", ["price"] = 300, ["label"] = "cctv monitor 2" },
        [31] = { ["object"] = "prop_cctv_cam_07a", ["price"] = 300, ["label"] = "cctv 3" },
        [32] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 5500, ["label"] = "flatscreen meubel" },
        [33] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 5500, ["label"] = "flatscreen meubel 2" },
        [34] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "dj set" },
        [35] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "serverrack" },
        [36] = { ["object"] = "apa_mp_h_str_avunitl_01_b", ["price"] = 5500, ["label"] = "flat screen furniture 3" },
        [37] = { ["object"] = "apa_mp_h_str_avunitl_04", ["price"] = 5500, ["label"] = "flat screen furniture 4" },
        [38] = { ["object"] = "apa_mp_h_str_avunitm_01", ["price"] = 5500, ["label"] = "flat screen furniture 5" },
        [39] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 5500, ["label"] = "flat screen furniture 6" },
        [40] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 5500, ["label"] = "flat screen furniture 7" },
        [41] = { ["object"] = "v_res_printer", ["price"] = 300, ["label"] = "printer" },
        [42] = { ["object"] = "apa_mp_h_acc_phone_01", ["price"] = 100, ["label"] = "old fashioned telephone" },
        [43] = { ["object"] = "v_res_mousemat", ["price"] = 300, ["label"] = "mouse pad" },
        [44] = { ["object"] = "v_res_pcheadset", ["price"] = 300, ["label"] = "headset" },
        [45] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "PC speaker" },
        [46] = { ["object"] = "ba_prop_battle_club_speaker_small", ["price"] = 500, ["label"] = "small box" },
        [47] = { ["object"] = "ba_prop_battle_club_speaker_med", ["price"] = 750, ["label"] = "box" },
        [48] = { ["object"] = "ba_prop_battle_club_speaker_large", ["price"] = 1000, ["label"] = "big box" },
        [49] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "PC speaker" },
        [50] = { ["object"] = "v_res_pcwoofer", ["price"] = 300, ["label"] = "PC subwoofer" },
        [51] = { ["object"] = "prop_controller_01", ["price"] = 300, ["label"] = "Controller" },
        [52] = { ["object"] = "prop_cs_remote_01", ["price"] = 300, ["label"] = "Remote control" },
        [53] = { ["object"] = "prop_portable_hifi_01", ["price"] = 300, ["label"] = "Radio" },
        [54] = { ["object"] = "prop_dj_deck_02", ["price"] = 300, ["label"] = "DJ table" },
        [55] = { ["object"] = "prop_speaker_01", ["price"] = 300, ["label"] = "Speaker" }			
    },
},}