general2 = {
    ['general2'] = {
    label = "Props",
    items = {
        [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["label"] = "A4 Pile" },
        [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["label"] = "40 oz" },
        [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["label"] = "Beer" },
        [4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["label"] = "Aviators" },
        [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["label"] = "Detail" },
        [6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["label"] = "Beers" },
        [7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["label"] = "Binoculars" },
        [8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["label"] = "Blox Spray" },
        [9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["label"] = "Bongos" },
        [10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["label"] = "Bong" },
        [11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["label"] = "Boombox" },
        [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["label"] = "Bowl Crisps" },
        [13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["label"] = "Candy" },
        [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["label"] = "Carrier bag" },
        [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["label"] = "Ceramic Jug" },
        [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["label"] = "Cigar Pack 1" },
        [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["label"] = "Cigar Pack 2" },
        [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["label"] = "Beer Box 2" },
        [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["label"] = "Binder" },
        [20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["label"] = "Cup" },
        [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["label"] = "Envelope" },
        [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["label"] = "Flute" },
        [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["label"] = "Duffel Bag" },
        [24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["label"] = "DVD" },
        [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["label"] = "DVD Case" },
        [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["label"] = "Film Reel" },
        [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["label"] = "Blind" },
        [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["label"] = "Bag" },
        [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["label"] = "Ironing Board" },
        [30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["label"] = "Katana" },
        [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["label"] = "Kettle" },
        [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["label"] = "Crate" },
        [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["label"] = "Petrol Can" },
        [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["label"] = "Sack" },
        [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["label"] = "Script Bottle" },
        [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["label"] = "Script Bottle 2" },
        [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["label"] = "Bin Bag" },
        [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["label"] = "Whiskey Bottle" },
        [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["label"] = "Bong" },
        [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["label"] = "Peanuts" },
        [41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["label"] = "Tumbler" },
        [42] = { ["object"] = "prop_weed_bottle", ["price"] = 100, ["label"] = "Weed koker" },
        [43] = { ["object"] = "p_cs_lighter_01", ["price"] = 100, ["label"] = "Lighter" },
        [44] = { ["object"] = "p_cs_papers_01", ["price"] = 100, ["label"] = "Rolling papers" },
        [45] = { ["object"] = "v_res_d_dildo_f", ["price"] = 100, ["label"] = "dildo Black" },
        [46] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["label"] = "dildo white" },
        [47] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["label"] = "Mommy's toy" },
        [48] = { ["object"] = "prop_champ_cool", ["price"] = 100, ["label"] = "Champagne cooler" },
        [49] = { ["object"] = "prop_champ_01b", ["price"] = 100, ["label"] = "champagnebottle" },
        [50] = { ["object"] = "prop_champ_flute", ["price"] = 100, ["label"] = "champagneglas" },
        [51] = { ["object"] = "ba_prop_club_champset", ["price"] = 300, ["label"] = "champagneset" },
        [52] = { ["object"] = "v_res_fa_candle01", ["price"] = 100, ["label"] = "candle blue" },
        [53] = { ["object"] = "v_res_fa_candle02", ["price"] = 100, ["label"] = "candle red" },
        [54] = { ["object"] = "v_res_fa_candle03", ["price"] = 100, ["label"] = "candle black" },
        [55] = { ["object"] = "v_res_fa_candle04", ["price"] = 100, ["label"] = "candle small" },
        [56] = { ["object"] = "v_med_bottles2", ["price"] = 100, ["label"] = "Chemicals" },
        [57] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["label"] = "Office stuf" },
        [58] = { ["object"] = "v_med_p_notebook", ["price"] = 100, ["label"] = "Note's" },
        [59] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 100, ["label"] = "mountain of weed" },
        [60] = { ["object"] = "ba_prop_battle_trophy_battler", ["price"] = 100, ["label"] = "fist trofee" },
        [61] = { ["object"] = "ba_prop_battle_trophy_no1", ["price"] = 100, ["label"] = "ster trofee" },
        [62] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "Golf bag" },
        [63] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "Garbage can" },
        [64] = { ["object"] = "prop_wooden_barrel", ["price"] = 100, ["label"] = "wooden vat" },
        [65] = { ["object"] = "bkr_prop_bkr_cash_scatter_01", ["price"] = 100, ["label"] = "scatter" },
        [66] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 100, ["label"] = "Cash" },
        [67] = { ["object"] = "bkr_prop_bkr_cash_roll_01", ["price"] = 100, ["label"] = "Cash roll" },
        [68] = { ["object"] = "bkr_prop_bkr_cashpile_04", ["price"] = 100, ["label"] = "pile of cash" },
        [69] = { ["object"] = "bkr_prop_weed_bigbag_open_01a", ["price"] = 100, ["label"] = "Weed open bag" },
        [70] = { ["object"] = "bkr_prop_weed_bigbag_02a", ["price"] = 100, ["label"] = "Weed bag 2" },
        [71] = { ["object"] = "bkr_prop_weed_bigbag_03a", ["price"] = 100, ["label"] = "Weed bag 3" },
        [72] = { ["object"] = "bkr_prop_weed_scales_01a", ["price"] = 100, ["label"] = "scales" },
        [73] = { ["object"] = "bkr_prop_weed_smallbag_01a", ["price"] = 100, ["label"] = "small bag" },
        [74] = { ["object"] = "prop_gold_bar", ["price"] = 100, ["label"] = "Gold Bar" },
        [75] = { ["object"] = "beerrow_world", ["price"] = 100, ["label"] = "beer bottles" },
        [76] = { ["object"] = "beerrow_local", ["price"] = 100, ["label"] = "beer bottles 2" },
        [77] = { ["object"] = "p_cs_bbbat_01", ["price"] = 100, ["label"] = "Bat" },
        [78] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["label"] = "handcuffs" },
        [79] = { ["object"] = "p_cs_joint_02", ["price"] = 100, ["label"] = "Joint" },
        [80] = { ["object"] = "p_ing_coffeecup_01", ["price"] = 100, ["label"] = "Coffee mug" },
        [81] = { ["object"] = "p_tumbler_cs2_s", ["price"] = 100, ["label"] = "Tumbler" },
        [82] = { ["object"] = "prop_turkey_leg_01", ["price"] = 100, ["label"] = "chicken leg" },
        [83] = { ["object"] = "prop_amb_donut", ["price"] = 100, ["label"] = "Donut" },
        [84] = { ["object"] = "prop_donut_02", ["price"] = 100, ["label"] = "Donut 2" },
        [85] = { ["object"] = "prop_bar_shots", ["price"] = 100, ["label"] = "Bar shots" },
        [86] = { ["object"] = "prop_bar_stirrers", ["price"] = 100, ["label"] = "Bar stirrers" },
        [87] = { ["object"] = "prop_beer_amopen", ["price"] = 100, ["label"] = "Beer open" },
        [88] = { ["object"] = "prop_beer_blr", ["price"] = 100, ["label"] = "Beer 1" },
        [89] = { ["object"] = "prop_beer_logger", ["price"] = 100, ["label"] = "Beer 2" },
        [90] = { ["object"] = "prop_beer_stzopen", ["price"] = 100, ["label"] = "Beer 3" },
        [91] = { ["object"] = "prop_bikerset", ["price"] = 100, ["label"] = "Biker Set" },
        [92] = { ["object"] = "prop_bottle_brandy", ["price"] = 100, ["label"] = "Bottle brandy" },
        [93] = { ["object"] = "prop_tequila_bottle", ["price"] = 100, ["label"] = "Tequila bottle" },
        [94] = { ["object"] = "prop_tequila", ["price"] = 100, ["label"] = "Tequila" },
        [95] = { ["object"] = "prop_bottle_cognac", ["price"] = 100, ["label"] = "Bottle of Cognac" },
        [96] = { ["object"] = "prop_bottle_macbeth", ["price"] = 100, ["label"] = "Bottle of Macbeth" },
        [97] = { ["object"] = "prop_brandy_glass", ["price"] = 100, ["label"] = "Brandy Glass" },
        [98] = { ["object"] = "prop_mug_01", ["price"] = 100, ["label"] = "Mug 1" },
        [99] = { ["object"] = "prop_mug_02", ["price"] = 100, ["label"] = "Mug 2" },
        [100] = { ["object"] = "prop_mug_03", ["price"] = 100, ["label"] = "Mug 3" },
        [101] = { ["object"] = "prop_optic_vodka", ["price"] = 100, ["label"] = "Vodka" },
        [102] = { ["object"] = "prop_optic_jd", ["price"] = 100, ["label"] = "JD" },
        [103] = { ["object"] = "prop_pint_glass_01", ["price"] = 100, ["label"] = "Pint Glass" },
        [104] = { ["object"] = "prop_pizza_box_03", ["price"] = 100, ["label"] = "Pizza box" },
        [105] = { ["object"] = "prop_sandwich_01", ["price"] = 100, ["label"] = "Sandwich" },
        [106] = { ["object"] = "prop_cava", ["price"] = 100, ["label"] = "Cava" },
        [107] = { ["object"] = "prop_drink_redwine", ["price"] = 100, ["label"] = "Red wine" },
        [108] = { ["object"] = "vodkarow", ["price"] = 100, ["label"] = "Vodka Row" },
        [109] = { ["object"] = "prop_cherenkov_02", ["price"] = 100, ["label"] = "Cherenkov" },
        [110] = { ["object"] = "prop_cherenkov_03", ["price"] = 100, ["label"] = "Cherenkov 2" },
        [111] = { ["object"] = "prop_cocktail_glass", ["price"] = 100, ["label"] = "Cocktail glass" },
        [112] = { ["object"] = "prop_cs_bottle_opener", ["price"] = 100, ["label"] = "Fles opener" },
        [113] = { ["object"] = "prop_food_bs_chips", ["price"] = 100, ["label"] = "Chips" },
        [114] = { ["object"] = "prop_cs_burger_01", ["price"] = 100, ["label"] = "Burger" },
        [115] = { ["object"] = "prop_cs_hand_radio", ["price"] = 100, ["label"] = "Hand radio" },
        [116] = { ["object"] = "prop_cs_hotdog_01", ["price"] = 100, ["label"] = "Hotdog" },
        [117] = { ["object"] = "prop_cs_milk_01", ["price"] = 100, ["label"] = "Milk" },
        [118] = { ["object"] = "prop_cs_panties", ["price"] = 100, ["label"] = "Panties" },
        [119] = { ["object"] = "prop_cs_steak", ["price"] = 100, ["label"] = "Meat" }			
    },
},}