lighting = {
    ['lighting'] = {
    label = "Lighting",
    items = {
        [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["label"] = "Desk Corp Lamp" },
        [2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["label"] = "Desk Lamp" },
        [3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["label"] = "Lamp AA" },
        [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["label"] = "Lamp 1" },
        [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["label"] = "Floor Lamp" },
        [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["label"] = "Lamp 2" },
        [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["label"] = "Table Lamp" },
        [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["label"] = "Table Lamp 2" },
        [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["label"] = "Bed Lamp" },
        [10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["label"] = "Plant Tongue Lamp" },
        [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["label"] = "Table Lamp 3" },
        [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["label"] = "Lamp Stand" },
        [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["label"] = "Lamp Stand 2" },
        [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["label"] = "Table Lamp 4" },
        [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["label"] = "Light Fan" },
        [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["label"] = "Tall Lamp" },
        [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["label"] = "Wall Light" },
        [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["label"] = "GC Lamp" },
        [19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["label"] = "Flickering Light" },
        [20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["label"] = "Side Wall Light" },
        -- [21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["label"] = "Test Light" },
        [21] = { ["object"] = "prop_wall_light_07a", ["price"] = 100, ["label"] = "lantaarn" },
        [22] = { ["object"] = "prop_wall_light_01a", ["price"] = 100, ["label"] = "Cheap lamp" },
        [23] = { ["object"] = "v_serv_tu_light2_", ["price"] = 100, ["label"] = "industrieel licht" },
        [24] = { ["object"] = "v_serv_tu_light3_", ["price"] = 100, ["label"] = "industrieel licht2" },
        [25] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 300, ["label"] = "hanging lamp" },
        [26] = { ["object"] = "v_med_p_floorlamp", ["price"] = 300, ["label"] = "Big lamp" },
        -- [27] = { ["object"] = "v_club_vu_lamp", ["price"] = 100, ["label"] = "Smal lamp" },
        [27] = { ["object"] = "ba_prop_battle_lights_wall_l_a", ["price"] = 100, ["label"] = "Wall lamp" },
        [28] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 300, ["label"] = "hanging lamp 2" },
        [29] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 300, ["label"] = "kroonluchter 2" },
        [30] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 100, ["label"] = "Wall lamp 2" },
        [31] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 100, ["label"] = "Wall lamp 3" },
        [32] = { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 300, ["label"] = "hanging lamp 3" },
        [33] = { ["object"] = "prop_oldlight_01b", ["price"] = 100, ["label"] = "wall lamp 4" },
        [34] = { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 100, ["label"] = "blue lamp" },
        [35] = { ["object"] = "apa_mp_h_ceiling_light_01", ["price"] = 100, ["label"] = "commercial" },
        [36] = { ["object"] = "apa_mp_h_ceiling_light_01_day", ["price"] = 100, ["label"] = "commercial 2" },
        [37] = { ["object"] = "apa_mp_h_ceiling_light_02", ["price"] = 100, ["label"] = "ceiling light" },
        [38] = { ["object"] = "apa_mp_h_ceiling_light_02_day", ["price"] = 100, ["label"] = "ceiling light 2" },
        [39] = { ["object"] = "ba_prop_battle_lights_ceiling_l_d", ["price"] = 100, ["label"] = "commercial 3" },
        [40] = { ["object"] = "ba_prop_battle_lights_ceiling_l_f", ["price"] = 100, ["label"] = "ceiling light 3" },
        [41] = { ["object"] = "ba_prop_battle_lights_ceiling_l_e", ["price"] = 100, ["label"] = "ceiling light 4" },
        [42] = { ["object"] = "apa_mp_h_floorlamp_a", ["price"] = 100, ["label"] = "floor lamp" },
        [43] = { ["object"] = "apa_mp_h_floorlamp_b", ["price"] = 100, ["label"] = "floor lamp 2" },
        [44] = { ["object"] = "apa_mp_h_floorlamp_c", ["price"] = 100, ["label"] = "floor lamp 3" },
        [45] = { ["object"] = "apa_mp_h_floor_lamp_int_08", ["price"] = 100, ["label"] = "floor lamp 4" },
        [46] = { ["object"] = "apa_mp_h_lampbulb_multiple_a", ["price"] = 100, ["label"] = "ceiling light 5" },
        [47] = { ["object"] = "apa_mp_h_lit_floorlamp_02", ["price"] = 100, ["label"] = "floor lamp 5" },
        [48] = { ["object"] = "apa_mp_h_lit_floorlampnight_14", ["price"] = 100, ["label"] = "floor lamp 6" },
        [49] = { ["object"] = "apa_mp_h_lit_floorlamp_03", ["price"] = 100, ["label"] = "floor lamp 7" },
        [50] = { ["object"] = "apa_mp_h_lit_floorlamp_06", ["price"] = 100, ["label"] = "floor lamp 8" },
        [51] = { ["object"] = "apa_mp_h_lit_floorlamp_10", ["price"] = 100, ["label"] = "floor lamp 9" },
        [52] = { ["object"] = "apa_mp_h_lit_floorlamp_13", ["price"] = 100, ["label"] = "floor lamp 10" },
        [53] = { ["object"] = "apa_mp_h_lit_floorlamp_17", ["price"] = 100, ["label"] = "floor lamp 11" },
        [54] = { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 100, ["label"] = "night light" },
        [55] = { ["object"] = "apa_mp_h_lit_lamptablenight_24", ["price"] = 100, ["label"] = "night light 2" },
        [56] = { ["object"] = "apa_mp_h_lit_lamptable_005", ["price"] = 100, ["label"] = "night light 3" },
        [57] = { ["object"] = "apa_mp_h_lit_lamptable_04", ["price"] = 100, ["label"] = "night light 4" },
        [58] = { ["object"] = "apa_mp_h_lit_lamptable_09", ["price"] = 100, ["label"] = "night light 5" },
        [59] = { ["object"] = "apa_mp_h_lit_lamptable_14", ["price"] = 100, ["label"] = "night light 6" },
        [60] = { ["object"] = "apa_mp_h_lit_lamptable_17", ["price"] = 100, ["label"] = "night light 7" },
        [61] = { ["object"] = "apa_mp_h_yacht_table_lamp_01", ["price"] = 100, ["label"] = "night light 8" }			
    },
},}