medical = {
    ['medical'] = {
    label = "Medical",
    items = {
        [1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["label"] = "Barrel" },
        [2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["label"] = "Ape Crate" },
        [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["label"] = "Ape Crate Large" },
        [4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["label"] = "Bed 1" },
        [5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["label"] = "Bed 2" },
        [6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["label"] = "Bed Table" },
        [7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["label"] = "Bench 1" },
        [8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["label"] = "Bench 2" },
        [9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["label"] = "Bench Center" },
        [10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["label"] = "Bench Set" },
        [11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["label"] = "Big Table" },
        [12] = { ["object"] = "v_med_bin", ["price"] = 150, ["label"] = "Bin" },
        [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["label"] = "Centrifuge" },
        [14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["label"] = "Cooler" },
        [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["label"] = "Monitor" },
        [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["label"] = "Autopsy Table" },
        [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["label"] = "Bin" },
        [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["label"] = "Trolley" },
        [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["label"] = "Chem" },
        [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["label"] = "BLM Table" },
        [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["label"] = "File Box" },
        [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["label"] = "File Cab" },
        [23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["label"] = "Hose" },
        [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["label"] = "Large Cupboard" },
        [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["label"] = "Lightbox" },
        [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["label"] = "Medstool" },
        [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["label"] = "Minifridge" },
        [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["label"] = "Papertowels" },
        [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["label"] = "Photocopy" },
        [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["label"] = "TV Stand" },
        [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["label"] = "Wall Unit" },
        [32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["label"] = "Exam light" },
        [33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["label"] = "Gas Tank" },
        [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["label"] = "Hazmat Scan" },
        [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["label"] = "Head Wall" },
        [36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["label"] = "Seating" },
        [37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["label"] = "Hosp Table" },
        [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["label"] = "Glove Box" },
        [39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["label"] = "Wastebin" },
        [40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["label"] = "Oscillator" },
        [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["label"] = "Health Pack" },
    },
},}