new = {
    ['new'] = {
        label = "New arrival",
        items = {
            -- arts
            [1] =  { ["object"] = "ex_p_h_acc_artwallm_01",              ["price"] = 1000,   ["label"] = "3D Wall Art" },
            [2] =  { ["object"] = "apa_mp_h_acc_artwalll_01",           ["price"] = 500,    ["label"] = "Red Big Wall Art" },
            [3] =  { ["object"] = "apa_mp_h_acc_artwalll_03",           ["price"] = 500,    ["label"] = "Blue Big Wall Art" },
            [4] =  { ["object"] = "apa_mp_h_acc_artwallm_02",           ["price"] = 500,    ["label"] = "Blue And White Big Wall Art" },
            [5] =  { ["object"] = "apa_mp_h_acc_artwallm_03",           ["price"] = 500,    ["label"] = "White and Mic color big Wall Art" },
            [6] =  { ["object"] = "apa_mp_h_acc_artwallm_04",           ["price"] = 500,    ["label"] = "Bloody Big Wall Art" },
            [7] =  { ["object"] = "apa_p_h_acc_artwalll_01",            ["price"] = 500,    ["label"] = "Blue Big Wall Art 2" },
            [8] = { ["object"] = "apa_p_h_acc_artwallm_04",            ["price"] = 500,    ["label"] = "Grey Wallpaper with big strips" },
            [9] = { ["object"] = "apa_p_h_acc_artwallm_04",            ["price"] = 400,    ["label"] = "Shirt Wall Frame" },
            [10] = { ["object"] = "ba_prop_battle_crate_art_02_bc",     ["price"] = 700,    ["label"] = "Box of Art stuff" },
            [11] = { ["object"] = "ex_prop_crate_art_02_sc",            ["price"] = 600,    ["label"] = "Create of Art stuff 1" },
            [12] = { ["object"] = "ex_prop_crate_art_bc",               ["price"] = 600,    ["label"] = "Create of Art stuff 2" },
            [13] = { ["object"] = "ex_prop_crate_art_sc",               ["price"] = 600,    ["label"] = "Create of Art stuff 3" },
            [14] = { ["object"] = "vw_prop_casino_art_console_01a",     ["price"] = 600,    ["label"] = "Console Art 1" },
            [15] = { ["object"] = "vw_prop_casino_art_console_02a",     ["price"] = 600,    ["label"] = "Console Art 2" },
            [16] = { ["object"] = "vw_prop_casino_art_skull_01b",       ["price"] = 400,    ["label"] = "Skull Art 1" },
            [17] = { ["object"] = "vw_prop_casino_art_skull_02a",       ["price"] = 400,    ["label"] = "Skull Art 2" },
            [18] = { ["object"] = "vw_prop_casino_art_skull_02b",       ["price"] = 400,    ["label"] = "Skull Art 3" },
            [19] = { ["object"] = "vw_prop_casino_art_skull_03a",       ["price"] = 400,    ["label"] = "Skull Art 4" },
            [20] = { ["object"] = "vw_prop_casino_art_skull_03b",       ["price"] = 400,    ["label"] = "Skull Art 5" },
            [21] = { ["object"] = "vw_prop_casino_art_bird_01a",        ["price"] = 600,    ["label"] = "Bird Arts" },
            [22] = { ["object"] = "vw_prop_casino_art_car_01a",         ["price"] = 800,    ["label"] = "Car Art 1" },
            [23] = { ["object"] = "vw_prop_casino_art_car_02a",         ["price"] = 800,    ["label"] = "Car Art 2" },
            [24] = { ["object"] = "vw_prop_casino_art_car_03a",         ["price"] = 800,    ["label"] = "Car Art 3" },
            [25] = { ["object"] = "vw_prop_casino_art_car_04a",         ["price"] = 800,    ["label"] = "Car Art 4" },
            [26] = { ["object"] = "vw_prop_casino_art_car_05a",         ["price"] = 800,    ["label"] = "Car Art 5" },
            [27] = { ["object"] = "vw_prop_casino_art_car_06a",         ["price"] = 800,    ["label"] = "Car Art 6" },
            [28] = { ["object"] = "vw_prop_casino_art_car_07a",         ["price"] = 800,    ["label"] = "Car Art 7" },
            [29] = { ["object"] = "vw_prop_casino_art_car_08a",         ["price"] = 800,    ["label"] = "Car Art 8" },
            [30] = { ["object"] = "vw_prop_casino_art_car_09a",         ["price"] = 800,    ["label"] = "Car Art 9" },
            [31] = { ["object"] = "vw_prop_casino_art_car_10a",         ["price"] = 800,    ["label"] = "Car Art 10" },
            [32] = { ["object"] = "vw_prop_casino_art_car_11a",         ["price"] = 800,    ["label"] = "Car Art 11" },
            [33] = { ["object"] = "vw_prop_casino_art_car_12a",         ["price"] = 800,    ["label"] = "Car Art 12" },
            [34] = { ["object"] = "vw_prop_casino_art_cherries_01a",    ["price"] = 800,    ["label"] = "Cherry Art" },
            [35] = { ["object"] = "vw_prop_casino_art_deer_01a",        ["price"] = 800,    ["label"] = "Miss Deer Art" },
            [36] = { ["object"] = "vw_prop_casino_art_dog_01a",         ["price"] = 800,    ["label"] = "Banana Dog" },
            [37] = { ["object"] = "vw_prop_casino_art_egg_01a",         ["price"] = 800,    ["label"] = "Alien Egg" },
            [38] = { ["object"] = "vw_prop_casino_art_grenade_01d",     ["price"] = 800,    ["label"] = "Fake Grenade" },
            [39] = { ["object"] = "vw_prop_casino_art_guitar_01a",      ["price"] = 800,    ["label"] = "Guitar 1" },
            [40] = { ["object"] = "vw_prop_casino_art_gun_01a",         ["price"] = 800,    ["label"] = "Weapon Frame 1" },
            [41] = { ["object"] = "vw_prop_casino_art_gun_02a",         ["price"] = 800,    ["label"] = "Weapon Frame 2" },
            [42] = { ["object"] = "vw_prop_casino_art_lampf_01a",       ["price"] = 800,    ["label"] = "Female Dancer lamp" },
            [43] = { ["object"] = "vw_prop_casino_art_lampm_01a",       ["price"] = 800,    ["label"] = "Male Dancer Lamp" },
            [44] = { ["object"] = "vw_prop_casino_art_mod_05a",         ["price"] = 800,    ["label"] = "Chicken Model" },
            [45] = { ["object"] = "vw_prop_casino_art_mod_06a",         ["price"] = 800,    ["label"] = "Colurful model" },
            [46] = { ["object"] = "vw_prop_casino_art_vase_01a",        ["price"] = 800,    ["label"] = "Vase 1" },
            [47] = { ["object"] = "vw_prop_casino_art_vase_02a",        ["price"] = 800,    ["label"] = "Vase 2" },
            [48] = { ["object"] = "vw_prop_casino_art_vase_03a",        ["price"] = 800,    ["label"] = "Vase 3" },
            [49] = { ["object"] = "vw_prop_casino_art_vase_04a",        ["price"] = 800,    ["label"] = "Vase 4" },
            [50] = { ["object"] = "vw_prop_casino_art_vase_05a",        ["price"] = 800,    ["label"] = "Vase 5" },
            [51] = { ["object"] = "vw_prop_casino_art_vase_10a",        ["price"] = 800,    ["label"] = "Vase 6" },
            [52] = { ["object"] = "vw_prop_casino_art_vase_11a",        ["price"] = 800,    ["label"] = "Vase 7" },
            [53] = { ["object"] = "vw_prop_casino_art_vase_12a",        ["price"] = 800,    ["label"] = "Vase 8" },
            [54] = { ["object"] = "vw_prop_art_football_01a",           ["price"] = 800,    ["label"] = "FootBall Art" },
            [55] = { ["object"] = "vw_prop_art_mic_01a",                ["price"] = 800,    ["label"] = "Mic Art" },
            [56] = { ["object"] = "vw_prop_art_pug_01a",                ["price"] = 800,    ["label"] = "Pug Art" },
            [57] = { ["object"] = "v_corp_bk_bust",                ["price"] = 800,    ["label"] = "Bust Art" },
            [58] = { ["object"] = "v_corp_bk_pens",                ["price"] = 800,    ["label"] = "pens Art" },
            --bathroom
            [59] =  { ["object"] = "v_corp_bombhum",              ["price"] = 2500,   ["label"] = "Washing Machine 1" },
            -- chairs
            [60] =  { ["object"] = "v_corp_bk_chair2",              ["price"] = 1000,   ["label"] = "Chair 1" },
            [61] =  { ["object"] = "v_corp_cd_recseat",              ["price"] = 1000,   ["label"] = "Chair 2" },
            [62] =  { ["object"] = "v_corp_facebeanbagb",              ["price"] = 1000,   ["label"] = "Chair 4" },
            [63] =  { ["object"] = "v_corp_lazychair",              ["price"] = 1000,   ["label"] = "Chair 5" },
            [64] =  { ["object"] = "v_corp_lngestool",              ["price"] = 1000,   ["label"] = "Chair 6" },
            -- electronic
            [65] =  { ["object"] = "v_corp_cd_intercom",              ["price"] = 1500,   ["label"] = "Intercom" },
            [66] =  { ["object"] = "v_corp_servercln2",              ["price"] = 2500,   ["label"] = "server 2" },
            [67] =  { ["object"] = "v_corp_servers1",              ["price"] = 3000,   ["label"] = "server 3" },
            -- extras
            [68] =  { ["object"] = "v_corp_bk_lflts",              ["price"] = 1000,   ["label"] = "Files Unit 1" },
            [69] =  { ["object"] = "v_corp_bk_lfltstand",              ["price"] = 1000,   ["label"] = "Files Unit 2" },
            [70] =  { ["object"] = "v_corp_bk_secpanel",              ["price"] = 5000,   ["label"] = "Security Panel" },
            [71] =  { ["object"] = "v_corp_bombbin",              ["price"] = 500,   ["label"] = "Bin 1" },
            [72] =  { ["object"] = "v_corp_cashtrolley_2",              ["price"] = 500,   ["label"] = "Cash Trolley" },
            --lights
            [73] =  { ["object"] = "v_corp_bk_lamp1",              ["price"] = 1000,   ["label"] = "Standing Lamp 1" },
            [74] =  { ["object"] = "v_corp_bk_lamp2",              ["price"] = 1000,   ["label"] = "Standing Lamp 2" },
            --
            [75] =  { ["object"] = "vw_prop_casino_art_plant_01a",              ["price"] = 1000,   ["label"] = "Plant 1" },
            [76] =  { ["object"] = "vw_prop_casino_art_plant_02a",              ["price"] = 1000,   ["label"] = "Plant 2" },
            [77] =  { ["object"] = "vw_prop_casino_art_plant_03a",              ["price"] = 1000,   ["label"] = "Plant 3" },
            [78] =  { ["object"] = "vw_prop_casino_art_plant_04a",              ["price"] = 1000,   ["label"] = "Plant 4" },
            [79] =  { ["object"] = "vw_prop_casino_art_plant_05a",              ["price"] = 1000,   ["label"] = "Plant 5" },
            [80] =  { ["object"] = "vw_prop_casino_art_plant_06a",              ["price"] = 1000,   ["label"] = "Plant 6" },
            [81] =  { ["object"] = "vw_prop_casino_art_plant_07a",              ["price"] = 1000,   ["label"] = "Plant 7" },
            [82] =  { ["object"] = "vw_prop_casino_art_plant_08a",              ["price"] = 1000,   ["label"] = "Plant 8" },
            [83] =  { ["object"] = "vw_prop_casino_art_plant_09a",              ["price"] = 1000,   ["label"] = "Plant 9" },
            [84] = { ["object"] = "vw_prop_casino_art_plant_10a",              ["price"] = 1000,   ["label"] = "Plant 10" },
            [85] = { ["object"] = "vw_prop_casino_art_plant_11a",              ["price"] = 1000,   ["label"] = "Plant 11" },
            [86] = { ["object"] = "vw_prop_casino_art_plant_12a",              ["price"] = 1000,   ["label"] = "Plant 12" },
            [87] = { ["object"] = "v_corp_plants",              ["price"] = 1000,   ["label"] = "Plant 13" },
            [88] = { ["object"] = "v_corp_plants",              ["price"] = 1000,   ["label"] = "Plant 14" },
            [89] = { ["object"] = "v_corp_potplant1",              ["price"] = 1000,   ["label"] = "Plant 15" },
            [90] = { ["object"] = "v_corp_potplant2",              ["price"] = 1000,   ["label"] = "Plant 16" },
            -- sofas
            [91] =  { ["object"] = "v_corp_bk_chair1",              ["price"] = 1000,   ["label"] = "Sofa 1" },
            -- storage
            [92] =  { ["object"] = "v_corp_bk_filecab",              ["price"] = 1000,   ["label"] = "Brown Filecab" },
            [93] =  { ["object"] = "v_corp_bk_filedraw",              ["price"] = 1000,   ["label"] = "Brown FileDrawer" },
            [94] =  { ["object"] = "v_corp_bk_filedraw",              ["price"] = 1000,   ["label"] = "Black Furniture Storage" },
            [95] =  { ["object"] = "v_corp_deskdraw",              ["price"] = 1000,   ["label"] = "Desk Drawer 1" },
            [96] =  { ["object"] = "v_corp_deskdrawdark01",              ["price"] = 1000,   ["label"] = "Desk Drawer 2" },
            [97] =  { ["object"] = "v_corp_deskseta",              ["price"] = 2500,   ["label"] = "Desk Set 1" },
            [98] =  { ["object"] = "v_corp_desksetb",              ["price"] = 3000,   ["label"] = "Desk Set 2" },
            [99] =  { ["object"] = "v_corp_filecabdark01",              ["price"] = 1000,   ["label"] = "Black Filecab" },
            [100] =  { ["object"] = "v_corp_filecabdark02",              ["price"] = 1000,   ["label"] = "Black FileDrawer" },
            [101] =  { ["object"] = "v_corp_offshelfclo",              ["price"] = 1000,   ["label"] = "Office File Shelf Closed" },
            [102] =  { ["object"] = "v_corp_offshelfdark",              ["price"] = 1000,   ["label"] = "Office File Shelf Dark" },
            -- tables
            [103] =  { ["object"] = "v_corp_cd_rectable",              ["price"] = 1000,   ["label"] = "Table 1" },
            [104] =  { ["object"] = "v_corp_conftable",              ["price"] = 1000,   ["label"] = "Table 2" },
            [105] =  { ["object"] = "v_corp_conftable2",              ["price"] = 1000,   ["label"] = "Table 3" },
            [106] =  { ["object"] = "v_corp_conftable3",              ["price"] = 1000,   ["label"] = "Table 4" },
            [107] =  { ["object"] = "v_corp_conftable4",              ["price"] = 1000,   ["label"] = "Table 5" },
            [108] =  { ["object"] = "v_corp_lidesk01",              ["price"] = 1000,   ["label"] = "Table 6" },
            [109] =  { ["object"] = "v_corp_maindesk",              ["price"] = 1000,   ["label"] = "Table 7" },
            [110] =  { ["object"] = "v_corp_officedesk",              ["price"] = 1000,   ["label"] = "Table 8" },
            [111] =  { ["object"] = "v_corp_officedesk_5",              ["price"] = 1000,   ["label"] = "Table 9" },
            [112] =  { ["object"] = "v_corp_officedesk003",              ["price"] = 1000,   ["label"] = "Table 10" },
            [113] =  { ["object"] = "v_corp_officedesk004",              ["price"] = 1000,   ["label"] = "Table 11" },
            [114] =  { ["object"] = "v_corp_officedesk1",              ["price"] = 1000,   ["label"] = "Table 12" },
            [115] =  { ["object"] = "v_corp_officedesk2",              ["price"] = 1000,   ["label"] = "Table 13" },
            -- walls
            [116] =  { ["object"] = "v_corp_bk_balustrade",              ["price"] = 1000,   ["label"] = "Wall 1" },
            [117] =  { ["object"] = "v_corp_cubiclefd",              ["price"] = 1000,   ["label"] = "Wall 2" },
            [118] =  { ["object"] = "v_corp_divide",              ["price"] = 1000,   ["label"] = "Wall 3" },
            [119] =  { ["object"] = "v_corp_go_glass2",              ["price"] = 1000,   ["label"] = "Wall 4" },
            [120] =  { ["object"] = "v_corp_partitionfd",              ["price"] = 1000,   ["label"] = "Wall 5" },
        }
    },
}