plants = {
    ['plants'] = {
    label = "Plants",
    items = {
        [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["label"] = "Plant Fib" },
        [2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["label"] = "Plant Bomb" },		
        [3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["label"] = "Plant Flowers" },	
        [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["label"] = "Plant Chinese" },	
        [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["label"] = "Plant Banana" },	
        [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["label"] = "Plant Palm" },	
        [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["label"] = "Plant Palm 2" },	
        [8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["label"] = "Plant Urn" },	
        [9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["label"] = "Plant Rubber" },	
        [10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["label"] = "Plant" },	
        [11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["label"] = "Plant Tree" },	
        [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["label"] = "Planter" },	
        [13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["label"] = "Flowers" },
        [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["label"] = "Flowers 1" },
        [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["label"] = "Flowers 2" },	
        [16] = { ["object"] = "v_res_m_vasefresh", ["price"] = 300, ["label"] = "FlowerFase" },
        [17] = { ["object"] = "v_res_rosevasedead", ["price"] = 300, ["label"] = "Pink Fase 2" },
        [18] = { ["object"] = "v_res_exoticvase", ["price"] = 300, ["label"] = "FlowerFase 2" },
        [19] = { ["object"] = "v_res_rosevase", ["price"] = 300, ["label"] = "Pink Fase" },
        [20] = { ["object"] = "prop_pot_plant_6a", ["price"] = 300, ["label"] = "Hanging ende plant" },
        [21] = { ["object"] = "prop_pot_plant_02a", ["price"] = 300, ["label"] = "Flower pot" },
        [22] = { ["object"] = "apa_mp_h_acc_plant_palm_01", ["price"] = 300, ["label"] = "palm plant" },
        [23] = { ["object"] = "prop_plant_interior_05a", ["price"] = 300, ["label"] = "flower box" },
        [24] = { ["object"] = "prop_plant_int_01a", ["price"] = 300, ["label"] = "plant" },
        [25] = { ["object"] = "prop_plant_int_01b", ["price"] = 300, ["label"] = "plant 2" },
        [26] = { ["object"] = "prop_plant_int_02a", ["price"] = 300, ["label"] = "plant 3" },
        [27] = { ["object"] = "prop_plant_int_02b", ["price"] = 300, ["label"] = "plant 4" },
        [28] = { ["object"] = "prop_plant_int_03a", ["price"] = 300, ["label"] = "plant 5" },
        [29] = { ["object"] = "prop_plant_int_03b", ["price"] = 300, ["label"] = "plant 6" },
        [30] = { ["object"] = "prop_plant_int_03c", ["price"] = 300, ["label"] = "plant 7" },
        [31] = { ["object"] = "prop_plant_int_04a", ["price"] = 300, ["label"] = "plant 8" },
        [32] = { ["object"] = "prop_plant_int_04c", ["price"] = 300, ["label"] = "plant 9" },
        [33] = { ["object"] = "prop_plant_int_05b", ["price"] = 300, ["label"] = "flower box 2" },
        [34] = { ["object"] = "prop_pot_plant_01a", ["price"] = 300, ["label"] = "plant pot 2" },
        [35] = { ["object"] = "prop_pot_plant_01b", ["price"] = 300, ["label"] = "plant pot 3" },
        [36] = { ["object"] = "prop_pot_plant_01c", ["price"] = 300, ["label"] = "plant pot 4" },
        [37] = { ["object"] = "prop_pot_plant_01d", ["price"] = 300, ["label"] = "plant pot 5" },
        [38] = { ["object"] = "prop_pot_plant_01e", ["price"] = 300, ["label"] = "plant pot 6" },
        [39] = { ["object"] = "prop_pot_plant_03b", ["price"] = 300, ["label"] = "plant pot 7" },
        [40] = { ["object"] = "prop_pot_plant_05a", ["price"] = 300, ["label"] = "plant pot 8" },
        [41] = { ["object"] = "prop_pot_plant_05b", ["price"] = 300, ["label"] = "plant pot 9" },
        [42] = { ["object"] = "p_int_jewel_plant_01", ["price"] = 300, ["label"] = "plant pot 10" },
        [43] = { ["object"] = "p_int_jewel_plant_02", ["price"] = 300, ["label"] = "plant pot 11" },
        [44] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 300, ["label"] = "plant pot 12" },
        [45] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 300, ["label"] = "plant pot 13" },
        [46] = { ["object"] = "apa_mp_h_acc_vase_flowers_03", ["price"] = 300, ["label"] = "plant pot 14" },
        [47] = { ["object"] = "apa_mp_h_acc_vase_flowers_04", ["price"] = 300, ["label"] = "plant pot 15" }				
    },
},}