small = {
    ['small'] = {
    label = "Details",
    items = {
        [1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["label"] = "Fig Cat" },
        [2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["label"] = "Fig Clown" },
        [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["label"] = "Fig Auth" },
        [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["label"] = "Fig Female" },
        [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["label"] = "Fig Flamenco" },
        [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["label"] = "Fig Girl" },
        [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["label"] = "Fig Girl Clown" },
        [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["label"] = "Fig Oblisk" },
        [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["label"] = "Fig Pillar" },
        [10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["label"] = "Teapot" },
        [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["label"] = "Sculpture 1" },
        [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["label"] = "Sculpture 2" },
        [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["label"] = "Sculpture 3" },
        [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["label"] = "Sculpture 4" },
        [15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["label"] = "Skateboard" },
        [16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["label"] = "Sketchpad" },
        [17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["label"] = "Tissues" },
        [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["label"] = "Basket" },
        [19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["label"] = "Bin" },
        [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["label"] = "Cushion 1" },
        [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["label"] = "Cushion 2" },
        [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["label"] = "Cushion 3" },
        [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["label"] = "Cushion 4" },
        [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["label"] = "Cushion 5" },
        [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["label"] = "Cushion 6" },
        [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["label"] = "Fruitbowl" },
        [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["label"] = "Sideboard" },
        [28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["label"] = "Idol 1" },
        [29] = { ["object"] = "v_res_r_fighorsestnd", ["price"] = 300, ["label"] = "Figurine black horse" },
        [30] = { ["object"] = "v_res_r_fighorse", ["price"] = 300, ["label"] = "Figurine big horse" },
        [31] = { ["object"] = "v_res_r_figdancer", ["price"] = 300, ["label"] = "Figurine dancer" },
        [32] = { ["object"] = "v_res_fa_idol02", ["price"] = 300, ["label"] = "olifanten Figurine" },
        [33] = { ["object"] = "v_res_m_statue", ["price"] = 300, ["label"] = "Sculpture" },
        [34] = { ["object"] = "v_20_ornaeagle", ["price"] = 300, ["label"] = "Figurine adelaar" },
        [35] = { ["object"] = "v_med_p_vaseround", ["price"] = 300, ["label"] = "Fase round" },
        [36] = { ["object"] = "ex_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "Fase Violet" },
        [37] = { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 300, ["label"] = "Art work" },
        [38] = { ["object"] = "apa_mp_h_acc_dec_sculpt_02", ["price"] = 300, ["label"] = "Art work 2" },
        [39] = { ["object"] = "ex_mp_h_acc_dec_plate_02", ["price"] = 300, ["label"] = "Art work 3" },
        [40] = { ["object"] = "apa_mp_h_acc_bowl_ceramic_01", ["price"] = 300, ["label"] = "schaal" },
        [41] = { ["object"] = "apa_mp_h_acc_dec_plate_01", ["price"] = 300, ["label"] = "Scale 2" },
        [42] = { ["object"] = "apa_mp_h_acc_vase_01", ["price"] = 300, ["label"] = "vase black and white" },
        [43] = { ["object"] = "apa_mp_h_acc_vase_02", ["price"] = 300, ["label"] = "vase red" },
        [44] = { ["object"] = "apa_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "vase" },
        [45] = { ["object"] = "apa_mp_h_acc_vase_06", ["price"] = 300, ["label"] = "vase black and white 2" }	
    },
},}