sofas = {
    ['sofas'] = {
    label = "Sofas",
    items = {
        [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["label"] = "Old couch" },
        [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["label"] = "Threesits couch" },
        [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["label"] = "Old chair" },
        [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["label"] = "Old treesits couch" },
        [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["label"] = "Old striped couch" },
        [6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["label"] = "Old 1 Seat Couch Yellow" },
        [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["label"] = "corner sofa" },
        [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["label"] = "corner sofa 2" },
        [9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["label"] = "couch 1" },
        [10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["label"] = "Couch 2" },
        [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["label"] = "Couch 3" },
        [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["label"] = "Couch 4" },
        [13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["label"] = "Couch 5" },
        [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["label"] = "Couch 6" },
        [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["label"] = "Couch 7" },
        [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["label"] = "Couch 8" },
        [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["label"] = "Couch 9" },
        [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["label"] = "Couch 10" },
        [19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["label"] = "Couch 11" },
        [20] = { ["object"] = "v_ilev_m_sofa", ["price"] = 2000, ["label"] = "White Couch" },
        [21] = { ["object"] = "v_med_p_sofa", ["price"] = 1000, ["label"] = "Lether Couch Brown" },
        -- [22] = { ["object"] = "v_club_officesofa", ["price"] = 500, ["label"] = "pauper Couch rood" },
        [22] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 1000, ["label"] = "Black Couch" },
        [23] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 5000, ["label"] = "corner sofa 3" },
        [24] = { ["object"] = "prop_couch_lg_02", ["price"] = 1000, ["label"] = "Couch hout" },
        [25] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 5000, ["label"] = "corner sofa 4" },
        [26] = { ["object"] = "apa_mp_h_yacht_sofa_02", ["price"] = 1000, ["label"] = "Brown Couch" },
        [27] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 5000, ["label"] = "White long Couch" },
        [28] = { ["object"] = "prop_couch_01", ["price"] = 1000, ["label"] = "sofa cushions" },
        [29] = { ["object"] = "prop_couch_03", ["price"] = 1000, ["label"] = "sofa yellow" },
        [30] = { ["object"] = "prop_couch_04", ["price"] = 1000, ["label"] = "leather sofa cushions" },
        [31] = { ["object"] = "prop_couch_lg_05", ["price"] = 500, ["label"] = "sofa corduroy" },
        [32] = { ["object"] = "prop_couch_lg_06", ["price"] = 1000, ["label"] = "leather sofa brown 2" },
        [33] = { ["object"] = "prop_couch_lg_07", ["price"] = 1000, ["label"] = "sofa cushions 2" },
        [34] = { ["object"] = "prop_couch_lg_08", ["price"] = 1000, ["label"] = "leather sofa brown 3" },
        [35] = { ["object"] = "prop_couch_sm1_07", ["price"] = 500, ["label"] = "leather sofa corner" },
        [36] = { ["object"] = "prop_couch_sm2_07", ["price"] = 500, ["label"] = "leather sofa straight" },
        [37] = { ["object"] = "prop_couch_sm_06", ["price"] = 500, ["label"] = "leather sofa small" },
        [38] = { ["object"] = "apa_mp_h_stn_sofa2seat_02", ["price"] = 1000, ["label"] = "love seat" },
        [39] = { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 5000, ["label"] = "corner sofa 5" },
        [40] = { ["object"] = "apa_mp_h_stn_sofacorn_06", ["price"] = 5000, ["label"] = "corner sofa 6" },
        [41] = { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 5000, ["label"] = "corner sofa 7" },
        [42] = { ["object"] = "apa_mp_h_stn_sofacorn_08", ["price"] = 5000, ["label"] = "corner sofa 8" },
        [43] = { ["object"] = "apa_mp_h_stn_sofacorn_09", ["price"] = 5000, ["label"] = "corner sofa 9" },
        [44] = { ["object"] = "ex_mp_h_off_sofa_003", ["price"] = 1000, ["label"] = "sofa blue fabric" },
        [45] = { ["object"] = "ex_mp_h_off_sofa_01", ["price"] = 1000, ["label"] = "sofa white leather" },
        [46] = { ["object"] = "ex_mp_h_off_sofa_02", ["price"] = 1000, ["label"] = "sofa black leather" },
        [47] = { ["object"] = "hei_heist_stn_sofa2seat_03", ["price"] = 1000, ["label"] = "sofa modern" },
        [48] = { ["object"] = "hei_heist_stn_sofa2seat_06", ["price"] = 1000, ["label"] = "couch brown" },
        [49] = { ["object"] = "hei_heist_stn_sofa3seat_01", ["price"] = 1000, ["label"] = "chaise lounge" },
        [50] = { ["object"] = "hei_heist_stn_sofa3seat_02", ["price"] = 1000, ["label"] = "sofa modern 2" },
        [51] = { ["object"] = "hei_heist_stn_sofa3seat_06", ["price"] = 1000, ["label"] = "sofa modern 3" },
        [52] = { ["object"] = "imp_prop_impexp_sofabed_01a", ["price"] = 1000, ["label"] = "sofa bed" },
        [53] = { ["object"] = "prop_t_sofa_02", ["price"] = 1000, ["label"] = "sofa bed2" }			
    },
},}