tables = {
    ['tables'] = {
    label = "Tables",
    items = {
        [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["label"] = "Coffee Table 1" },
        [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["label"] = "Round Table" },
        [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["label"] = "Small Side Table" },
        [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["label"] = "Table A" },
        [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["label"] = "Table B" },
        [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["label"] = "Table C" },
        [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["label"] = "Dining Table" },
        [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["label"] = "Coffee Table 2" },
        [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["label"] = "Low Table" },
        [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["label"] = "Bed Table" },
        [11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["label"] = "Desk" },
        [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["label"] = "Side Table" },
        [13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["label"] = "Console Table" },
        [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["label"] = "Dining Table 2" },
        [15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["label"] = "Console H Table" },
        [16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["label"] = "Stool?" },
        [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["label"] = "Sideboard Table" },
        [18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["label"] = "Table 2" },
        [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["label"] = "Tv Table" },
        [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["label"] = "Tv Table Tall" },
        [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["label"] = "Med Coffee Table" },
        [22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["label"] = "Med Desk" },
        [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["label"] = "Yacht Table 1" },
        [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["label"] = "Yacht Table 2" },
        [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["label"] = "Yacht Table 3" },
        [26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["label"] = "CSR Table" },
        [27] = { ["object"] = "v_res_mconsoletrad", ["price"] = 250, ["label"] = "high side table" },
        [28] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 500, ["label"] = "Office tabel" },
        [29] = { ["object"] = "v_ret_tablesml", ["price"] = 350, ["label"] = "Side table  marillaux" },
        [30] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 500, ["label"] = "koffie table Brown" },
        [31] = { ["object"] = "apa_mp_h_yacht_side_table_01", ["price"] = 300, ["label"] = "Side table Brown" },
        [32] = { ["object"] = "apa_mp_h_yacht_side_table_02", ["price"] = 300, ["label"] = "ronde Side table" },
        [33] = { ["object"] = "apa_mp_h_tab_sidelrg_04", ["price"] = 300, ["label"] = "ronde Side table 2" },
        -- [34] = { ["object"] = "v_club_vu_table", ["price"] = 300, ["label"] = "Coverd Table" },
        [34] = { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 500, ["label"] = "koffieTable glas" },
        [35] = { ["object"] = "bkr_prop_weed_table_01b", ["price"] = 100, ["label"] = "clapTable" },
        [36] = { ["object"] = "ba_prop_int_trad_table", ["price"] = 300, ["label"] = "Stand Table" },
        [37] = { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 750, ["label"] = "Side table glas" },
        [38] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 750, ["label"] = "koffieTable modern" },
        [39] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 1000, ["label"] = "dinner Table glas" },
        [40] = { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 5000, ["label"] = "desk + setup" },
        [41] = { ["object"] = "apa_mp_h_tab_coffee_07", ["price"] = 1000, ["label"] = "triangular side table" },
        [42] = { ["object"] = "apa_mp_h_tab_coffee_08", ["price"] = 1000, ["label"] = "white side table" },
        [43] = { ["object"] = "apa_mp_h_tab_sidelrg_01", ["price"] = 1000, ["label"] = "glass side table" },
        [44] = { ["object"] = "apa_mp_h_tab_sidelrg_02", ["price"] = 1000, ["label"] = "glass side table 2" },
        [45] = { ["object"] = "apa_mp_h_tab_sidesml_01", ["price"] = 1000, ["label"] = "folding table" },
        [46] = { ["object"] = "ba_prop_int_edgy_table_01", ["price"] = 500, ["label"] = "table marble" },
        [47] = { ["object"] = "ba_prop_int_edgy_table_02", ["price"] = 500, ["label"] = "table marble high" },
        [48] = { ["object"] = "apa_mp_h_tab_sidelrg_01", ["price"] = 1000, ["label"] = "glass side table" },
        [49] = { ["object"] = "xm_prop_lab_desk_01", ["price"] = 1000, ["label"] = "lab table" }			
    },
},}