Config = {}


Config.Keys = {
    ['ESC'] = 322, ['F1'] = 288, ['F2'] = 289, ['F3'] = 170, ['F5'] = 166, ['F6'] = 167, ['F7'] = 168, ['F8'] = 169, ['F9'] = 56, ['F10'] = 57,
    ['~'] = 243, ['1'] = 157, ['2'] = 158, ['3'] = 160, ['4'] = 164, ['5'] = 165, ['6'] = 159, ['7'] = 161, ['8'] = 162, ['9'] = 163, ['-'] = 84, ['='] = 83, ['BACKSPACE'] = 177,
    ['TAB'] = 37, ['Q'] = 44, ['W'] = 32, ['E'] = 38, ['R'] = 45, ['T'] = 245, ['Y'] = 246, ['U'] = 303, ['P'] = 199, ['['] = 39, [']'] = 40, ['ENTER'] = 18,
    ['CAPS'] = 137, ['A'] = 34, ['S'] = 8, ['D'] = 9, ['F'] = 23, ['G'] = 47, ['H'] = 74, ['K'] = 311, ['L'] = 182,
    ['LEFTSHIFT'] = 21, ['Z'] = 20, ['X'] = 73, ['C'] = 26, ['V'] = 0, ['B'] = 29, ['N'] = 249, ['M'] = 244, [','] = 82, ['.'] = 81,
    ['LEFTCTRL'] = 36, ['LEFTALT'] = 19, ['SPACE'] = 22, ['RIGHTCTRL'] = 70,
    ['HOME'] = 213, ['PAGEUP'] = 10, ['PAGEDOWN'] = 11, ['DELETE'] = 178,
    ['LEFT'] = 174, ['RIGHT'] = 175, ['TOP'] = 27, ['DOWN'] = 173,
}




Config.Locations = {
    -- ["exit"] = {x = -564.46, y = 273.89, z = 83.02, h = 166.89, r = 1.0},
    ["stash"] = {x = 314.37, y = -1261.15, z = 24.78, h = 83.49, r = 1.0},
    ["duty"] = {x = 296.61, y = -1253.01, z = 29.42, h = 344.81, r = 1.0},
    ["storage"] = {x = 302.47, y = -1278.04, z = 29.42, h = 270.43, r = 1.0}, 
    ["storage2"] = {x = 290.85, y = -1276.55, z = 29.42, h = 84.04, r = 1.0},
    ["storage3"] = {x = 331.53, y = -1261.29, z = 24.78, h = 272.88, r = 1.0},
    ["beerfill"] = {x = 316.0, y = -1263.91, z = 25.14, h = 89.92, r = 1.0}, 
    ["openstash"] = {x = 293.74, y = -1255.08, z = 29.42, h = 0.83, r = 1.0},
    ["openstash2"] = {x = 478.78, y = 2588.66, z = 43.27, h = 295.57, r = 1.0},
    ["vehicle"] = {x = 296.67, y = -1247.05, z = 28.94, h = 88.55},
}

Config.Vehicles = {
    ["moonbeam3"] = "ShopOne Vehicle",
}

Config.shopone = {
    label = "Shop One Storage",
    slots = 45,
    items = {
        [1] = {
            name = "bread",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 1,
        },

        [2] = {
            name = "veggies",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 2,
        },
        
        [3] = {
            name = "sauce",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 3,
        },

        [4] = {
            name = "bun",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 4,
        },

        [5] = {
            name = "vegpatty",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 5,
        },

        [6] = {
            name = "chickenpatty",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 6,
        },

        [7] = {
            name = "cheese",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 7,
        },

        [8] = {
            name = "potato",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 8,
        },

        [9] = {
            name = "oil",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 9,
        },

        [10] = {
            name = "icecream",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "milk",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 11,
        },

        [12] = {
            name = "chocochips",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "teapouch",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 13,
        },

        [14] = {
            name = "coffeepouch",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "sugar",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "brownies",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "cookies",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "pasta",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "knor",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "manchow",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "golgappa",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "gsauce",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "belachi",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "gulabjamun",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "water_bottle",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "paan",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "rosogulla",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "masala",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "paneer",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "roll",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "cuttedchicken",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "flour",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 32,
        },
        [33] = {
            name = "butter",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 33,
        },
        [34] = {
            name = "egg",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 34,
        },
        [35] = {
            name = "whiskey",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 35,
        },
        [36] = {
            name = "vodka",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 36,
        },
        [37] = {
            name = "vine",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 37,
        },
        [38] = {
            name = "champagne",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 38,
        },
        [39] = {
            name = "tequila",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 39,
        },
        [40] = {
            name = "monster",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 40,
        },
        [41] = {
            name = "redbull",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 41,
        },
        [42] = {
            name = "salt",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 42,
        },
        [43] = {
            name = "cigarette",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 43,
        },
        [44] = {
            name = "onion",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 44,
        },
        
    }
}

Config.shopone2 = {
    label = "Shop One Storage",
    slots = 1,
    items = {
        [1] = {
            name = "empty_bottle",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 1,
        },
        
    }
}