Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10
}
Config.Linux = true -- True if linux
Config.TweetDuration = 12 -- How many hours to load tweets (12 will load the past 12 hours of tweets)
Config.DarkWebDuration = 48
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.dept = {
    'police',
    'doctor',
    'mechanic'
}
Config.VPN = 'sandwich'
Config.PhoneApplications = {
    ["details"] = {
        app = "details",
        color = "#5db9fc",
        color2 = "#008eff",
        icon = "fas fa-info-circle",
        tooltipText = "Details",
        tooltipPos = "top",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["phone"] = {
        app = "phone",
        color = "#51da80",
        color2 = "#009436",
        icon = "fas fa-phone-volume",
        tooltipText = "Phone",
        tooltipPos = "top",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#8bfc76",
        color2 = "#18d016",
        icon = "fas fa-comment",
        tooltipText = "Messages",
        tooltipPos = "top",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        color2 = "#4c5558",
        icon = "fas fa-cog",
        tooltipText = "Settings",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["ping"] = {
        app = "ping",
        color = "#6d10f5",
        color2 = "#4b67ef",
        icon = "fas fa-map-marker-alt",
        tooltipText = "Ping",
        tooltipPos = "top",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "#009ee5",
        color2 = "#87d9e7",
        icon = "fas fa-envelope",
        tooltipText = "Mail",
        style = "font-size: 3vh";
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ["advert"] = {
        app = "advert",
        color = "#ffc900",
        color2 = "#f7c816",
        icon = "fas fa-bullhorn",
        tooltipText = "Advertisements",
        style = "font-size: 2vh";
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#151515",
        color2 = "#161616",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        style = "color: #2cabe0; font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ["garage"] = {
        app = "garage",
        color = "#ff8077",
        color2 = "#bb345d",
        icon = "fas fa-car",
        tooltipText = "Vehicles",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ["debt"] = {
        app = "debt",
        color = "#fdfeff",
        color2 = "#d5e6fa",
        icon = "fas fa-ad",
        tooltipText = "Billing",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ["wenmo"] = {
        app = "wenmo",
        color = "#151515",
        color2 = "#161616",
        icon = "fas fa-ad",
        tooltipText = "Money Transfer",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ["documents"] = {
        app = "documents",
        color = "#f15ac1",
        color2 = "#aa4edd",
        icon = "fas fa-sticky-note",
        tooltipText = "Notepad",
        style = "font-size: 3.3vh";
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["houses"] = {
        app = "houses",
        color = "#42a042",
        color2 = "#3f9e4a",
        icon = "fas fa-house-user",
        tooltipText = "Houses",
        style = "font-size: 3vh";
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    -- ["crypto"] = {
    --     app = "crypto",
    --     color = "#000000",
    --     color2 = "#000000",
    --     icon = "fab fa-bitcoin",
    --     tooltipText = "Crypto",
    --     style = "font-size: 2.7vh";
    --     job = false,
    --     blockedjobs = {},
    --     slot = 22,
    --     Alerts = 0,
    -- },
    ["jobcenter"] = {
        app = "jobcenter",
        color = "#151515",
        color2 = "#161616",
        icon = "fas fa-map-marked-alt",
        tooltipText = "GPS",
        style = "color: #78bdfd; font-size: 2.7vh";
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    -- ["employment"] = {
    --     app = "employment",
    --     color = "#151515",
    --     color2 = "#161616",
    --     icon = "fas fa-ad",
    --     tooltipText = "Employment",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 21,
    --     Alerts = 0,
    -- },
    -- ["lsbn"] = {
    --     app = "lsbn",
    --     color = "#151515",
    --     color2 = "#161616",
    --     icon = "fas fa-ad",
    --     tooltipText = "LSBN",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 17,
    --     Alerts = 0,
    -- },
    ["lawyers"] = {
        app = "lawyers",
        color = "#26d4ce",
        color2 = "#1e9c98",
        icon = "fas fa-briefcase",
        tooltipText = "Services",
        tooltipPos = "bottom",
        style = "font-size: 3vh";
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    -- ["casino"] = {
    --     app = "casino",
    --     color = "#000100",
    --     color2 = "#000100",
    --     icon = "fas fa-gem",
    --     tooltipText = "Casino",
    --     tooltipPos = "bottom",
    --     style = "font-size: 2.7vh";
    --     job = false,
    --     blockedjobs = {},
    --     slot = 23,
    --     Alerts = 0,
    -- },
    ["calculator"] = {
        app = "calculator",
        color = "#c94001",
        color2 = "#9c3100",
        icon = "fas fa-calculator",
        tooltipText = "Calculator",
        tooltipPos = "bottom",
        style = "font-size: 2.5vh";
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
    ["gallery"] = {
        app = "gallery",
        color = "#189ec0",
        color2 = "#14819c",
        icon = "fas fa-images",
        tooltipText = "Gallery",
        tooltipPos = "bottom",
        style = "font-size: 2.7vh";
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        color2 = "#8070d5",
        icon = "fas fa-file-contract",
        tooltipText = "Invoices",
        style = "font-size: 2.7vh";
        job = false,
        blockedjobs = {},
        slot = 18,
        Alerts = 0,
    },
    ["racing"] = {
        app = "racing",
        color = "#353b48",
        color2 = "#242830",
        icon = "fas fa-flag-checkered",
        tooltipText = "Racing",
        style = "font-size: 3vh";
        job = false,
        blockedjobs = {},
        slot = 19,
        Alerts = 0,
    },
    ["meos"] = {
        app = "meos",
        color = "#004682",
        color2 = "#00325c",
        icon = "fas fa-ad",
        tooltipText = "MDT",
        job = "police",
        blockedjobs = {},
        slot = 23,
        Alerts = 0,
    },
    ["darkweb"] = {
        app = "darkweb",
        color = "#0F0F0F",
        color2 = "#00325c",
        icon = "fas fa-hat-cowboy",
        tooltipText = "Darkweb",
        job = false,
        blockedjobs = {},
        slot = 21,
        Alerts = 0,
    },
    ["vpn"] = {
        app = "vpn",
        color = "#0F0F0F",
        color2 = "#ffffff",
        icon = "fas fa-hat-cowboy",
        tooltipText = "VPN",
        job = false,
        blockedjobs = {},
        slot = 22,
        Alerts = 0,
    },
    ["duty"] = {
        app = "duty",
        color = "#FF0000",
        color2 = "#00325c",
        icon = "fas fa-sign-in-alt",
        tooltipText = nil,
        job = false,
        blockedjobs = {},
        slot = 20,
        Alerts = 0,
    },
    
    -- ["store"] = {
    --     app = "store",
    --     color = "#a9fd78",
    --     color2 = "#86c95f",
    --     icon = "fas fa-dollar-sign",
    --     tooltipText = "My Bank",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 21,
    --     Alerts = 0,
    -- },
    -- ["camera"] = {
    --     app = "camera",
    --     color = "#AC1D2C",
    --     color2 = "#25d366",
    --     icon = "fas fa-camera",
    --     tooltipText = "Camera",
    --     tooltipPos = "bottom",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 15,
    --     Alerts = 0,
    -- },
}
Config.MaxSlots = 28

Config.StoreApps = {
    ["duty"] = {
        app = "duty",
        color = "#FF0000",
        color2 = "#00325c",
        icon = "fas fa-sign-in-alt",
        tooltipText = nil,
        job = false,
        blockedjobs = {},
        slot = 20,
        Alerts = 0,
        password = true,
        creator = "QBCore",
        title = "Territory",
    },
    ["territory"] = {
        app = "territory",
        color = "#353b48",
        icon = "fas fa-globe-europe",
        tooltipText = "Territorium",
        style = "";
        job = false,
        blockedjobs = {},
        slot = 28,
        Alerts = 0,
        password = true,
        creator = "QBCore",
        title = "Territory",
    },
}

Config.JobCenter = {
    [1] = {
        job = "unemployed",
        label = "Amazon",
        Coords = {60.68, 103.56},
    },
    [2] = {
        job = "unemployed",
        label = "Taxi Driver",
        Coords = {909.49, -177.24},
    },
    [3] = {
        job = "unemployed",
        label = "Towing",
        Coords = {-188.74, -1179.89},
    },
    [4] = {
        job = "unemployed",
        label = "Weazel News",
        Coords = {-552.29, -925.59},
    },
    [5] = {
        job = "unemployed",
        label = "Trash Collector",
        Coords = {884.15, -2179.42},
    },
    [6] = {
        job = "unemployed",
        label = "Bus Driver",
        Coords = {462.22, -641.15},
    },
    [7] = {
        job = "unemployed",
        label = "MCD",
        Coords = {82.79, 279.2},
    },
    [8] = {
        job = "unemployed",
        label = "Bean Coffee",
        Coords = {-629.63, 234.39},
    },
    [9] = {
        job = "unemployed",
        label = "CatCafe",
        Coords = {-581.06, -1066.23},
    },
    [10] = {
        job = "unemployed",
        label = "L S Custom",
        Coords = {-339.05, -135.53},
    },
    [11] = {
        job = "unemployed",
        label = "PDM",
        Coords = {-51.86, -1109.36},
    },
    [12] = {
        job = "unemployed",
        label = "EDM",
        Coords = {-803.21, -224.27},
    },
    [13] = {
        job = "unemployed",
        label = "Garage A",
        Coords = {-475.31, -818.73},
    },
    [14] = {
        job = "unemployed",
        label = "Garage B",
        Coords = {273.43, -343.99},
    },
    [15] = {
        job = "unemployed",
        label = "Garage C",
        Coords = {69.84, 12.6},
    },
    [16] = {
        job = "unemployed",
        label = "Garage D",
        Coords = {-330.01, -780.33},
    },
    [17] = {
        job = "unemployed",
        label = "Garage E",
        Coords = {-1160.86, -741.41},
    },
    [18] = {
        job = "unemployed",
        label = "Garage F",
        Coords = {-1183.1, -1511.11},
    },
    [19] = {
        job = "unemployed",
        label = "PDM Parking",
        Coords = {-154.3, -1175.53},
    },
    [20] = {
        job = "unemployed",
        label = "Garage H",
        Coords = {78.34, 6418.74},
    },
    [21] = {
        job = "unemployed",
        label = "Garage I",
        Coords = {1726.21, 3707.16},
    },
    [22] = {
        job = "unemployed",
        label = "Garage J",
        Coords = {934.95, 3606.59},
    },
    [23] = {
        job = "unemployed",
        label = "Garage K",
        Coords = {1137.77, 2663.54},
    },
    [24] = {
        job = "unemployed",
        label = "Garage L",
        Coords = {-796.86, -2024.85},
    },
    [25] = {
        job = "unemployed",
        label = "Garage M",
        Coords = {364.37, 297.83},
    },
    [26] = {
        job = "unemployed",
        label = "Tuner Garage",
        Coords = {163.05, -3003.18},
    },
    [27] = {
        job = "unemployed",
        label = "Legion Garage",
        Coords = {215.9499, -809.698},
    },
    [28] = {
        job = "unemployed",
        label = "Mechanic Garage",
        Coords = {-387.78, -128.35},
    },
}