bathroom = {
    ['bathroom'] = {
        label = "Bathroom",
        items = {
            [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["label"] = "Toilet 1" },
            [2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["label"] = "Toilet 2" },
            [3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["label"] = "Toilet 3" },
            [4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["label"] = "Sink 1" },
            [5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["label"] = "Sink 2" },
            [6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["label"] = "Sink 3" },
            [7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["label"] = "Sink 4" },
            [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["label"] = "Soap Dispenser" },
            [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["label"] = "Shower Rack" },
            [10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["label"] = "Hand Dryer 1" },
            [11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["label"] = "Hand Dryer 2" },
            [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["label"] = "Towel Rail 1" },
            [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["label"] = "Towel Rail 2" },
            [14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["label"] = "Towel 1" },
            [15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["label"] = "Towel 2" },
            [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["label"] = "Towel 3" },
            [17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["label"] = "Bath" },
            [18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["label"] = "Sink" },
            [19] = { ["object"] = "v_ilev_mm_faucet", ["price"] = 100, ["label"] = "tap" },
            [20] = { ["object"] = "v_res_tre_washbasket", ["price"] = 250, ["label"] = "Washing mand" },
            [21] = { ["object"] = "prop_toilet_soap_02", ["price"] = 100, ["label"] = "Tray Soap" },
            [22] = { ["object"] = "prop_bar_sink_01", ["price"] = 100, ["label"] = "Sink" },
            [23] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 1000, ["label"] = "Bath" },
            [24] = { ["object"] = "prop_toilet_brush_01", ["price"] = 1000, ["label"] = "Brush" },
            [25] = { ["object"] = "prop_toilet_roll_01", ["price"] = 1000, ["label"] = "Toilet rol" },
            [26] = { ["object"] = "prop_toilet_roll_02", ["price"] = 1000, ["label"] = "Toilet rol 2" },
            [27] = { ["object"] = "prop_toilet_shamp_01", ["price"] = 1000, ["label"] = "Shampoo" },
            [28] = { ["object"] = "prop_toilet_shamp_02", ["price"] = 1000, ["label"] = "Shampoo 2" }			
        },
    },
}