general4 = {
    ['general4'] = {
    label = "Random 2",
    items = {
        [1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["label"] = "Dummy" },
        [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["label"] = "Egg Clock" },
        [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["label"] = "E Guitar 1" },
        [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["label"] = "E Guitar 2" },
        [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["label"] = "E Guitar 2" },
        [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["label"] = "Feed Sack" },
        [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["label"] = "Floor Duster" },
        [8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["label"] = "Fruit Basket" },
        [9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["label"] = "Duster" },
        [10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["label"] = "Grapes" },
        [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["label"] = "Hotel Clock" },
        [12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["label"] = "Idol Case" },
        [13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["label"] = "Jewels" },
        [14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["label"] = "Jewels" },
        [15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["label"] = "Jewels" },
        [16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["label"] = "Jewels" },
        [17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["label"] = "Jewels" },
        [18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["label"] = "Jewels" },
        [19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["label"] = "Jewels" },
        [20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["label"] = "Display Tray" },
        [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["label"] = "Display Tray" },
        [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["label"] = "Display Tray" },
        [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["label"] = "Display Tray" },
        [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["label"] = "Display Tray" },
        [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["label"] = "Display Tray" },
        [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["label"] = "Display Tray" },
        [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["label"] = "Display Tray" },
        [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["label"] = "Green Screen" },
        [29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["label"] = "Handbag" },
        [30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["label"] = "Jerry Can" },
        [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["label"] = "Keypad 1" },
        [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["label"] = "Keypad 2" },
        [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["label"] = "Suitcase 1" },
        [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["label"] = "Suitcase 2" },
        [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["label"] = "Suitcase 3"},
        [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["label"] = "Rasberry Clean" },
        [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["label"] = "Paper Bag" },
        [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["label"] = "Shopping Bags" },
        [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["label"] = "Shopping Bags 2" },
        [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["label"] = "Yoga Mat 1" },
        [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["label"] = "Yoga Mat 2" },
        [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["label"] = "Yoga Mat 3" },
        [43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["label"] = "Sax" },
        [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["label"] = "SOCCER Ball" },
        [45] = { ["object"] = "p_watch_01", ["price"] = 100, ["label"] = "Watch 1" },
        [46] = { ["object"] = "p_watch_02", ["price"] = 100, ["label"] = "Watch 2" },
        [47] = { ["object"] = "p_watch_03", ["price"] = 100, ["label"] = "Watch 3" },
        [48] = { ["object"] = "p_watch_04", ["price"] = 100, ["label"] = "Watch 4" },
        [49] = { ["object"] = "p_watch_05", ["price"] = 100, ["label"] = "Watch 5" },
        [50] = { ["object"] = "p_watch_06", ["price"] = 100, ["label"] = "Watch 6" },
        [51] = { ["object"] = "apa_mp_h_acc_candles_01", ["price"] = 100, ["label"] = "candle" },
        [52] = { ["object"] = "apa_mp_h_acc_candles_02", ["price"] = 100, ["label"] = "candle 2" },
        [53] = { ["object"] = "apa_mp_h_acc_candles_04", ["price"] = 100, ["label"] = "candle 3" },
        [54] = { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 100, ["label"] = "candle 4" },
        [55] = { ["object"] = "apa_mp_h_acc_fruitbowl_02", ["price"] = 100, ["label"] = "fruit bowl" },
        [56] = { ["object"] = "apa_mp_h_acc_tray_01", ["price"] = 100, ["label"] = "thingies" },
        [57] = { ["object"] = "prop_bskball_01", ["price"] = 100, ["label"] = "Basketball" },
        [58] = { ["object"] = "prop_cs_wrench", ["price"] = 100, ["label"] = "Wrench" },
        [59] = { ["object"] = "prop_cs_bowie_knife", ["price"] = 100, ["label"] = "Bowie Knife" },
        [60] = { ["object"] = "prop_w_me_hatchet", ["price"] = 100, ["label"] = "Hatchet" }			
    },
},}