general = {
    ['general'] = {
    label = "General",
    items = {
        [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["label"] = "Bean Bag 1" },
        [2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["label"] = "White Vase" },
        [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["label"] = "Padded Wall" },
        [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["label"] = "Item" },
        [5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["label"] = "Whips" },
        [6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["label"] = "Mags" },
        [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["label"] = "Mags Open" },
        [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["label"] = "Mag Tidy" },
        [9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["label"] = "Yoga Mat 1" },
        [10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["label"] = "Yoga Mat 2" },
        [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["label"] = "Aftershave" },
        [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["label"] = "Flowers" },
        [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["label"] = "Fruitbowl" },
        [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["label"] = "Laundry Basket" },
        [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["label"] = "Pouf" },
        [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["label"] = "Sculpture" },
        [17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["label"] = "Mag Rack" },
        [18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["label"] = "Jewel Box" },
        [19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["label"] = "Bin" },
        [20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["label"] = "Ornate Bowl" },
        [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["label"] = "Bronze Vase" },
        [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["label"] = "Chalk Board" },
        [23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["label"] = "Dresser" },
        [24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["label"] = "Linth" },
        [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["label"] = "Ashtray" },
        [26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["label"] = "Candle" },
        [27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["label"] = "Candle Large" },
        [28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["label"] = "Scales" },
        [29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["label"] = "Bed Pillow" },
        [30] = { ["object"] = "v_med_cor_whiteboard", ["price"] = 300, ["label"] = "whiteboard" },
        [31] = { ["object"] = "prop_ashtray_01", ["price"] = 100, ["label"] = "asbak black" },
        [32] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 100, ["label"] = "asbak stone" },
        -- [33] = { ["object"] = "v_24_wdr_mesh_rugs", ["price"] = 500, ["label"] = "Rag" },
        [33] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 500, ["label"] = "Rug 2" },
        [34] = { ["object"] = "ex_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "Rug 3" },
        [35] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 500, ["label"] = "Rug 4" },
        [36] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 500, ["label"] = "Rug 5" },
        [37] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "Rug 6" },
        -- [38] = { ["object"] = "v_club_rack", ["price"] = 500, ["label"] = "kledingrek" }	
    },
},}