general3 = {
    ['general3'] = {
    label = "Random",
    items = {
        [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["label"] = "CSR Bin" },
        [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["label"] = "Basket" },
        [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["label"] = "GC Bag 1" },
        [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["label"] = "GC Bag 2" },
        [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["label"] = "GC Bin" },
        [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["label"] = "Cash Register" },
        [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["label"] = "GC Chair 01" },
        [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["label"] = "GC Chair 02" },
        [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["label"] = "Clock" },
        [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["label"] = "Prod 1" },
        [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["label"] = "Prod 2" },
        [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["label"] = "Prod 3" },
        [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["label"] = "Prod 4" },
        [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["label"] = "Prod 5" },
        [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["label"] = "Prod 6" },
        [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["label"] = "HD Unit 1" },
        [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["label"] = "HD Unit 2" },
        [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["label"] = "Fridge" },
        [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["label"] = "Bag 1" },
        [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["label"] = "Bag 2" },
        [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["label"] = "Book 1" },
        [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["label"] = "Book 2" },
        [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["label"] = "Book 3" },
        [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["label"] = "Book 4" },
        [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["label"] = "Cam" },
        [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["label"] = "First Aid" },
        [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["label"] = "Hero" },
        [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["label"] = "Mag 1" },
        [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["label"] = "Mag 2" },
        [30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["label"] = "Skull" },
        [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["label"] = "Guitar" },
        [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["label"] = "Handbag" },
        [33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["label"] = "Case" },
        [34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["label"] = "Big Bag" },
        [35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["label"] = "Bonesaw" },
        [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["label"] = "Fertilizer" },
        [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["label"] = "Shopping Bag" },
        [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["label"] = "Vial" },
        [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["label"] = "Ragdoll" }, 
        [40] = { ["object"] = "v_res_fa_book03", ["price"] = 100, ["label"] = "boek kamasutra" },
        [41] = { ["object"] = "prop_weight_rack_02", ["price"] = 500, ["label"] = "dumbbellrek" },
        [42] = { ["object"] = "prop_weight_bench_02", ["price"] = 500, ["label"] = "Couchdrukset" },
        [43] = { ["object"] = "prop_tool_broom", ["price"] = 100, ["label"] = "Broom" },
        [44] = { ["object"] = "prop_fire_exting_2a", ["price"] = 100, ["label"] = "Fire extinguisher" },
        [45] = { ["object"] = "v_res_vacuum", ["price"] = 100, ["label"] = "vacuum cleaner" },
        [46] = { ["object"] = "v_ret_gc_fan", ["price"] = 100, ["label"] = "Fan" },
        [47] = { ["object"] = "prop_paint_stepl01b", ["price"] = 100, ["label"] = "ladder" },
        [48] = { ["object"] = "bkr_prop_weed_bucket_01b", ["price"] = 100, ["label"] = "Fertilizer" },
        -- [49] = { ["object"] = "v_club_vusnaketank", ["price"] = 500, ["label"] = "terrarium" },
        [51] = { ["object"] = "prop_pooltable_02", ["price"] = 1500, ["label"] = "poolTable" },
        [52] = { ["object"] = "prop_pool_rack_02", ["price"] = 100, ["label"] = "poolcues" },
        [53] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "dj set" },
        [54] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "serverrack" }
    },
},}