kitchen = {
    ['kitchen'] = {
    label = "Kitchen",
    items = {
        [1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["label"] = "Washer 1" },
        [2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["label"] = "Washer 2" },
        [3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["label"] = "Washer 3" },
        [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["label"] = "Washing Basket" },
        [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["label"] = "Fridge 1" },
        [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["label"] = "Fridge 2" },
        [7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["label"] = "Fridge 3" },
        [8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["label"] = "Fridge 4" },
        [9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["label"] = "Cooker" },
        [10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["label"] = "Microwave 1" },
        [11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["label"] = "Microwave 2" },
        [12] = { ["object"] = "prop_wok", ["price"] = 150, ["label"] = "Wok" },
        [13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["label"] = "Cake Plate" },
        [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["label"] = "Chopping Board" },
        [15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["label"] = "Utensils" },
        [16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["label"] = "Pestle" },
        [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["label"] = "PaperRoll 1" },
        [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["label"] = "PaperRoll 2" },
        [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["label"] = "Pot 1" },
        [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["label"] = "Pot 2" },
        [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["label"] = "Pot 3" },
        [22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["label"] = "Pot 4" },
        [23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["label"] = "Pot 5" },
        [24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["label"] = "Pot 6" },
        [25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["label"] = "Pot 7" },
        [26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["label"] = "Pot Rack" },
        [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["label"] = "Juicer" },
        [28] = { ["object"] = "v_res_ovenhobmod", ["price"] = 1000, ["label"] = "Stove" },
        [29] = { ["object"] = "v_res_mkniferack", ["price"] = 100, ["label"] = "Knive" },
        [30] = { ["object"] = "v_res_mchopboard", ["price"] = 100, ["label"] = "Cutting plank" },
        [31] = { ["object"] = "prop_cs_kitchen_cab_l", ["price"] = 750, ["label"] = "Kitchen Cupboard Wide" },
        [32] = { ["object"] = "prop_cs_kitchen_cab_r", ["price"] = 500, ["label"] = "Kitchen cupboard smal" },
        [33] = { ["object"] = "prop_cs_kitchen_cab_r", ["price"] = 500, ["label"] = "Kitchen cupboard smal" },
        [34] = { ["object"] = "v_res_tre_fridge", ["price"] = 500, ["label"] = "refrigerator" },
        [35] = { ["object"] = "apa_mp_h_acc_coffeemachine_01", ["price"] = 500, ["label"] = "coffee machine" },
        [36] = { ["object"] = "p_new_j_counter_02", ["price"] = 500, ["label"] = "Counter" },
        [37] = { ["object"] = "prop_bar_pump_09", ["price"] = 500, ["label"] = "Pump 1" },
        [38] = { ["object"] = "prop_bar_pump_01", ["price"] = 500, ["label"] = "Pump 2" },
        [39] = { ["object"] = "prop_chip_fryer", ["price"] = 500, ["label"] = "Chips fryer" },
        [40] = { ["object"] = "prop_cleaver", ["price"] = 500, ["label"] = "Knife" },
        [41] = { ["object"] = "prop_coffee_mac_02", ["price"] = 500, ["label"] = "coffee machine" },
        [42] = { ["object"] = "prop_coffee_mac_01", ["price"] = 500, ["label"] = "coffee machine 2" },
        [43] = { ["object"] = "prop_cs_fork", ["price"] = 500, ["label"] = "Fork" },
        [44] = { ["object"] = "prop_cs_sink_filler", ["price"] = 500, ["label"] = "Sink filler" },
        [45] = { ["object"] = "prop_toaster_01", ["price"] = 500, ["label"] = "Toaster" },
        [46] = { ["object"] = "prop_cs_plate_01", ["price"] = 500, ["label"] = "Plate" },
        [47] = { ["object"] = "prop_foodprocess_01", ["price"] = 500, ["label"] = "Food Process" },
        [48] = { ["object"] = "prop_food_sugarjar", ["price"] = 500, ["label"] = "Sugar Bowl" },
        [49] = { ["object"] = "prop_juice_dispenser", ["price"] = 500, ["label"] = "Dispencer" },
        [50] = { ["object"] = "prop_knife_stand", ["price"] = 500, ["label"] = "Knife holder" },
        [51] = { ["object"] = "prop_knife", ["price"] = 500, ["label"] = "Knife 2" },
        [52] = { ["object"] = "prop_micro_04", ["price"] = 500, ["label"] = "Microwave 4" },
        [53] = { ["object"] = "v_ret_fh_plate3", ["price"] = 500, ["label"] = "Plate 5" },
        [54] = { ["object"] = "v_ilev_tt_plate01", ["price"] = 500, ["label"] = "Plate 6" },
        [55] = { ["object"] = "v_res_fa_grater", ["price"] = 500, ["label"] = "Grater" },
        [56] = { ["object"] = "v_res_tt_pizzaplate", ["price"] = 500, ["label"] = "Pizza Plate" },
        [57] = { ["object"] = "v_ret_247_ketchup2", ["price"] = 500, ["label"] = "Ketchup" }			
    },
},}