storage = {
    ['storage'] = {
    label = "Storage",
    items = {
        [1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["label"] = "Cabinet Large" },
        [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["label"] = "Dressing Table" },
        [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["label"] = "Side Unit" },
        [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["label"] = "Side Unit" },
        [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["label"] = "Side Unit" },
        [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["label"] = "Bed Unit" },
        [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["label"] = "Tv Unit" },
        [8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["label"] = "Dresser Unit" },
        [9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["label"] = "Bottoman Unit" },
        [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["label"] = "Console Unit" },
        [11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["label"] = "Cupboard Unit" },
        [12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["label"] = "Chest Unit" },
        [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["label"] = "Mason Unit" },
        [14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["label"] = "Armoire Unit" },
        [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["label"] = "Side Unit" },
        [16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["label"] = "Desk Unit" },
        [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["label"] = "Side Unit" },
        [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["label"] = "Side Unit 2" },
        [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["label"] = "Book Unit" },
        [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["label"] = "Box Unit" },
        [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["label"] = "Storage Unit" },
        [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["label"] = "Wardrobe Unit" },
        [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["label"] = "Wood Unit" },
        [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["label"] = "Bean Bag 1" },
        [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["label"] = "Mil Crate 1" },
        [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["label"] = "Mil Crate 2" },
        [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["label"] = "Safe" },
        [28] = { ["object"] = "prop_toolchest_05", ["price"] = 5000, ["label"] = "Crafting Bench" },
        [29] = { ["object"] = "v_corp_filecablow", ["price"] = 500, ["label"] = "Filing cabinet Low" },
        [30] = { ["object"] = "v_corp_filecabtall", ["price"] = 500, ["label"] = "Filing cabinet High" },
        [31] = { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 500, ["label"] = "Large modern cupboard" },
        [32] = { ["object"] = "v_ilev_frnkwarddr1", ["price"] = 500, ["label"] = "Cupboard franklin" },
        [33] = { ["object"] = "prop_coathook_01", ["price"] = 100, ["label"] = "Coat rack" },
        [34] = { ["object"] = "v_corp_lowcabdark01", ["price"] = 500, ["label"] = "Filing cabinetLow black" },
        [35] = { ["object"] = "v_corp_tallcabdark01", ["price"] = 500, ["label"] = "Filing cabinet High black" },
        [36] = { ["object"] = "v_corp_cabshelves01", ["price"] = 1000, ["label"] = "Filing cabinet black" },
        [37] = { ["object"] = "v_corp_offshelf", ["price"] = 1000, ["label"] = "Filing cabinet groot" },
        -- [38] = { ["object"] = "v_61_lng_mesh_unitc", ["price"] = 500, ["label"] = "Bookcase white" },
        -- [38] = { ["object"] = "ba_wardrobe", ["price"] = 500, ["label"] = "kledingkast" },
        [38] = { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 750, ["label"] = "Cupboard  modern" },
        [39] = { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 750, ["label"] = "Cupboard  modern 2" },
        [40] = { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 750, ["label"] = "Bookcase 2" },
        [41] = { ["object"] = "apa_mp_h_str_sideboardl_11", ["price"] = 750, ["label"] = "Cupboard  modern 3" },
        [42] = { ["object"] = "imp_prop_impexp_parts_rack_03a", ["price"] = 750, ["label"] = "car parts" },
        [43] = { ["object"] = "imp_prop_impexp_parts_rack_04a", ["price"] = 750, ["label"] = "car parts 2" },
        [44] = { ["object"] = "imp_prop_impexp_parts_rack_05a", ["price"] = 750, ["label"] = "car parts 3" },
        [45] = { ["object"] = "apa_mp_h_bed_chestdrawer_02", ["price"] = 750, ["label"] = "chest of drawers" },
        [46] = { ["object"] = "hei_heist_bed_chestdrawer_04", ["price"] = 750, ["label"] = "chest of drawers 2" },
        [47] = { ["object"] = "prop_rub_cabinet", ["price"] = 50, ["label"] = "rusted filing cabinet" },
        [48] = { ["object"] = "prop_tv_cabinet_03", ["price"] = 750, ["label"] = "tv little cupboard" },
        [49] = { ["object"] = "prop_tv_cabinet_04", ["price"] = 750, ["label"] = "tv little cupboard 2" },
        [50] = { ["object"] = "prop_tv_cabinet_05", ["price"] = 750, ["label"] = "tv little cupboard 3" },
        [51] = { ["object"] = "apa_mp_h_str_shelffreel_01", ["price"] = 750, ["label"] = "ikea closet" },
        [52] = { ["object"] = "apa_mp_h_str_sideboardl_13", ["price"] = 750, ["label"] = "cabinet modern 4" },
        [53] = { ["object"] = "apa_mp_h_str_sideboardl_14", ["price"] = 750, ["label"] = "cabinet modern 5" },
        [54] = { ["object"] = "apa_mp_h_str_sideboardm_02", ["price"] = 750, ["label"] = "cabinet modern 6" },
        [55] = { ["object"] = "bkr_prop_biker_garage_locker_01", ["price"] = 750, ["label"] = "Biker Locker" },
        [56] = { ["object"] = "gr_prop_gr_bench_04b", ["price"] = 750, ["label"] = "Biker Bench" }			
    },
},}